extern const GeoLayout gs_area_1_geo[];
extern const GeoLayout gs_area_1[];
extern const Collision gs_area_1_collision[];
extern const MacroObject gs_area_1_macro_objs[];
extern Vtx gs_dl_Gass_mesh_vtx_0[23];
extern Gfx gs_dl_Gass_mesh_tri_0[];
extern Vtx gs_dl_Gate_001_mesh_vtx_0[4];
extern Gfx gs_dl_Gate_001_mesh_tri_0[];
extern Vtx gs_dl_Gate_002_mesh_vtx_0[4];
extern Gfx gs_dl_Gate_002_mesh_tri_0[];
extern Vtx gs_dl_Gate_003_mesh_vtx_0[4];
extern Gfx gs_dl_Gate_003_mesh_tri_0[];
extern Vtx gs_dl_Gate_004_mesh_vtx_0[39];
extern Gfx gs_dl_Gate_004_mesh_tri_0[];
extern Vtx gs_dl_Goomboss_mesh_vtx_0[509];
extern Gfx gs_dl_Goomboss_mesh_tri_0[];
extern Vtx gs_dl_Goomboss_001_mesh_vtx_0[474];
extern Gfx gs_dl_Goomboss_001_mesh_tri_0[];
extern Vtx gs_dl_Goomboss_002_mesh_vtx_0[55];
extern Gfx gs_dl_Goomboss_002_mesh_tri_0[];
extern Vtx gs_dl_Goomboss_003_mesh_vtx_0[44];
extern Gfx gs_dl_Goomboss_003_mesh_tri_0[];
extern Vtx gs_dl_Goomboss_004_mesh_vtx_0[143];
extern Gfx gs_dl_Goomboss_004_mesh_tri_0[];
extern Vtx gs_dl_Goomboss_005_mesh_vtx_0[20];
extern Gfx gs_dl_Goomboss_005_mesh_tri_0[];
extern Vtx gs_dl_Goomboss_006_mesh_vtx_0[70];
extern Gfx gs_dl_Goomboss_006_mesh_tri_0[];
extern Vtx gs_dl_Goomboss_007_mesh_vtx_0[10];
extern Gfx gs_dl_Goomboss_007_mesh_tri_0[];
extern Vtx gs_dl_Goomboss_008_mesh_vtx_0[8];
extern Gfx gs_dl_Goomboss_008_mesh_tri_0[];
extern Vtx gs_dl_Goomboss_009_mesh_vtx_0[29];
extern Gfx gs_dl_Goomboss_009_mesh_tri_0[];
extern Vtx gs_dl_Goomboss_010_mesh_vtx_0[28];
extern Gfx gs_dl_Goomboss_010_mesh_tri_0[];
extern Vtx gs_dl_Goomboss_011_mesh_vtx_0[40];
extern Gfx gs_dl_Goomboss_011_mesh_tri_0[];
extern Vtx gs_dl_Goomboss_012_mesh_vtx_0[534];
extern Gfx gs_dl_Goomboss_012_mesh_tri_0[];
extern Vtx gs_dl_Rims_mesh_vtx_0[28];
extern Gfx gs_dl_Rims_mesh_tri_0[];

extern Gfx gs_dl_Gass_mesh[];
extern Gfx gs_dl_Gate_001_mesh[];
extern Gfx gs_dl_Gate_002_mesh[];
extern Gfx gs_dl_Gate_003_mesh[];
extern Gfx gs_dl_Gate_004_mesh[];
extern Gfx gs_dl_Goomboss_mesh[];
extern Gfx gs_dl_Goomboss_001_mesh[];
extern Gfx gs_dl_Goomboss_002_mesh[];
extern Gfx gs_dl_Goomboss_003_mesh[];
extern Gfx gs_dl_Goomboss_004_mesh[];
extern Gfx gs_dl_Goomboss_005_mesh[];
extern Gfx gs_dl_Goomboss_006_mesh[];
extern Gfx gs_dl_Goomboss_007_mesh[];
extern Gfx gs_dl_Goomboss_008_mesh[];
extern Gfx gs_dl_Goomboss_009_mesh[];
extern Gfx gs_dl_Goomboss_010_mesh[];
extern Gfx gs_dl_Goomboss_011_mesh[];
extern Gfx gs_dl_Goomboss_012_mesh[];
extern Gfx gs_dl_Rims_mesh[];
extern Gfx gs_dl_material_revert_render_settings[];

