#include "levels/gs/texture_include.inc.c"
#include "levels/gs/area_1/collision.inc.c"
#include "levels/gs/area_1/macro.inc.c"
#include "levels/gs/area_1/spline.inc.c"
#include "levels/gs/model.inc.c"
